repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        exclude: rednotebook/external/.*\.py
      - id: ruff-format
        exclude: rednotebook/external/.*\.py
