#! /usr/bin/env python

import optparse
import sys

from wake import Vulture


def parse_args():
    def csv(option, opt, value, parser):
        setattr(parser.values, option.dest, value.split(','))
    parser = optparse.OptionParser()
    parser.add_option('--exclude', action='callback', callback=csv,
                      type="string", default=[])
    parser.add_option('-v', '--verbose', action='store_true')
    options, args = parser.parse_args()
    return options, args


if __name__ == '__main__':
    options, args = parse_args()
    vulture = Vulture(exclude=options.exclude, verbose=options.verbose)
    vulture.scavenge(args)
    vulture.report()
